# Edit your ~/.bash_profile file (for Mac) and add the following to the end.

alias gfps='git fetch && git pull && git status'
alias gs='git status'
alias gf='git fetch'
alias gp='git pull'
alias gc='git checkout '
alias gpsh='git push '
alias gl='git log '
alias ga='git add '
alias gd='git diff '
alias gco='git commit '
alias gr='git reset '
alias gsh='git show '
alias gb='git branch '
alias gm='git merge '
